### ISSUE TITLE
Editor?

### ISSUE THREAD

**Issue by k3n** [evnbr/syntax-highlight#2]
Hi! Github's weekly email sent me here, but I can't tell from looking around which editor this configuration is intended for...

**Comment by evnbr** [comment]
This is just an in-browser demo. You can find an [emacs version here](https://github.com/ankurdave/color-identifiers-mode), and without me realizing [kDevelop had this feature way before I made this demo](http://zwabel.wordpress.com/2009/01/08/c-ide-evolution-from-syntax-highlighting-to-semantic-highlighting/). I'll add some better documentation!

**Comment by k3n** [comment]
Oh ok, thanks for the info. It's really cool and I like the idea, was hoping I'd be able to use it in one of my editors.
