### ISSUE TITLE
second `var text =`

### ISSUE THREAD

**Issue by tomByrer** [evnbr/syntax-highlight#3]
https://github.com/evanbrooks/syntax-highlight/blob/gh-pages/script.js#L60
I am still learning JavaScript; is there a ninja optimization reason why you declare `var text` a second time please?

Overall, I like your script; would be handy to switch between this function & the normal syntax highlighting in editors!

**Comment by evnbr** [comment]
Nope good catch. That whole section is a super hacky way to determine the cursor position, not very good code to learn from :/
